### ISSUE TITLE
您好，这个仿真环境是否可以进行路径规划算法相应的研究？

### ISSUE THREAD

**Issue by hxj0316** [Mr-Tony921/xju-robot#1]
您好，请问该仿真环境的所有代码您是已经全部上传以及开源吗？我是否可以使用您的仿真环境进行相应的路径规划算法相关的研究工作呢？具体就是我基于A*算法进行了一些改进工作，已经在MATLAB环境下进行算法的验证了，现在想着可以在ros环境下在次进行更加符合机器人工作的一些研究。

**Comment by hxj0316** [comment]
您好，我今天在编译您的程序时，出现了如下的错误，但是当我重新删除所有文件从头开始新建文件夹开始编译，这个错误又没有了。这项错误发生在当我把其他的路径规划算法和xju_robot_master这个文件夹放在同一个目录中的时候会发生。请问这是什么原因呢？
![2022-12-06 16-36-32 的屏幕截图](https://user-images.githubusercontent.com/66103957/205862249-67ff2ab8-c852-43a9-8973-074116ab472e.png)

**Comment by Mr-Tony921** [comment]
> 您好，请问该仿真环境的所有代码您是已经全部上传以及开源吗？我是否可以使用您的仿真环境进行相应的路径规划算法相关的研究工作呢？具体就是我基于A*算法进行了一些改进工作，已经在MATLAB环境下进行算法的验证了，现在想着可以在ros环境下在次进行更加符合机器人工作的一些研究。

我还会做一些更新，已上传的这部分工作是开源的，你可以自由使用

**Comment by Mr-Tony921** [comment]
> 您好，我今天在编译您的程序时，出现了如下的错误，但是当我重新删除所有文件从头开始新建文件夹开始编译，这个错误又没有了。这项错误发生在当我把其他的路径规划算法和xju_robot_master这个文件夹放在同一个目录中的时候会发生。请问这是什么原因呢？ ![2022-12-06 16-36-32 的屏幕截图](https://user-images.githubusercontent.com/66103957/205862249-67ff2ab8-c852-43a9-8973-074116ab472e.png)

应该是环境变量的问题，可能你之前的工程也有costmap plugin，然后xju工程链接到你原来的include目录，没有找到新加的keepout layer，ros工程可以分开目录使用的，你单独source xju的setup.bash然后编译就好了

**Comment by hxj0316** [comment]
> > 您好，我今天在编译您的程序时，出现了如下的错误，但是当我重新删除所有文件从头开始新建文件夹开始编译，这个错误又没有了。这项错误发生在当我把其他的路径规划算法和xju_robot_master这个文件夹放在同一个目录中的时候会发生。请问这是什么原因呢？ ![2022-12-06 16-36-32 的屏幕截图](https://user-images.githubusercontent.com/66103957/205862249-67ff2ab8-c852-43a9-8973-074116ab472e.png)
> 
> 应该是环境变量的问题，可能你之前的工程也有costmap plugin，然后xju工程链接到你原来的include目录，没有找到新加的keepout layer，ros工程可以分开目录使用的，你单独source xju的setup.bash然后编译就好了

您好，我今天只在单独的工作空间下进行xju工程的编译，它依旧还是出现了我上面截图所说的那个问题，我很疑惑。我在该工作空间下只有xju一项工程，应该不存在您说的链接到原来的include目录的问题

**Comment by Mr-Tony921** [comment]
> > > 您好，我今天在编译您的程序时，出现了如下的错误，但是当我重新删除所有文件从头开始新建文件夹开始编译，这个错误又没有了。这项错误发生在当我把其他的路径规划算法和xju_robot_master这个文件夹放在同一个目录中的时候会发生。请问这是什么原因呢？ ![2022-12-06 16-36-32 的屏幕截图](https://user-images.githubusercontent.com/66103957/205862249-67ff2ab8-c852-43a9-8973-074116ab472e.png)
> > 
> > 
> > 应该是环境变量的问题，可能你之前的工程也有costmap plugin，然后xju工程链接到你原来的include目录，没有找到新加的keepout layer，ros工程可以分开目录使用的，你单独source xju的setup.bash然后编译就好了
> 
> 您好，我今天只在单独的工作空间下进行xju工程的编译，它依旧还是出现了我上面截图所说的那个问题，我很疑惑。我在该工作空间下只有xju一项工程，应该不存在您说的链接到原来的include目录的问题

之前没有加dependencies，你更新试下

**Comment by jsj441805126** [comment]
> 您好，请问该仿真环境的所有代码您是已经全部上传以及开源吗？我是否可以使用您的仿真环境进行相应的路径规划算法相关的研究工作呢？具体就是我基于A*算法进行了一些改进工作，已经在MATLAB环境下进行算法的验证了，现在想着可以在ros环境下在次进行更加符合机器人工作的一些研究。

您好，我想也是想用xju的这个工程进行路径规划相关算法的研究，目前想把改进后的A*算法在这个框架下进行测试，请问您是如何进行的，可以交流以下吗?如果可以的话您是否方便给我您的联系方式
