### ISSUE TITLE
无法找到头文件costmap_2d/keepoutzone.h

### ISSUE THREAD

**Issue by EricDowney1** [Mr-Tony921/xju-robot#10]
你好，在文件/xju-robot/src/pnc/node/mbf_bridge_node.cpp中，导入了头文件#include "costmap_2d/keepoutzone.h'，但是在costmap_2d文件中，并没有找到keepoutzone.h。

**Comment by little-litter** [comment]
俺也一样

**Comment by jsj441805126** [comment]
+1

**Comment by biqibaopaidasao** [comment]
你好，请问以下你是怎么解决这个问题的@EricDowney1

**Comment by xu810201** [comment]
https://github.com/Mr-Tony921/navigation.git 下载这个包，重新编译解决

**Comment by biqibaopaidasao** [comment]
大佬，还是不行啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-Tony921/xju-robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mr-Tony921/xju-robot] 无法找到头文件costmap_2d/keepoutzone.h (Issue #10)





 
https://github.com/Mr-Tony921/navigation.git 下载这个包，重新编辑解决
