### ISSUE TITLE
lio-sam好像缺少了

### ISSUE THREAD

**Issue by AllenOpensourceAny** [Mr-Tony921/xju-robot#11]
lio-sam好像缺少了，在thirdparty目录下没看到

**Comment by Mr-Tony921** [comment]
已经把大型的第三方工程从thirdparty删除了，避免每次更新下载过多，启动脚本保留下来放在工程里，如果需要相关的模块，自行下载即可，小橘工程没有对这些大型工程做改动

**Comment by AllenOpensourceAny** [comment]
up主，你好，将lio-sam加入第三方库，编译不通过，有没有完整的工程，分享下，谢谢！



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月18日 11:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Mr-Tony921/xju-robot] lio-sam好像缺少了 (Issue #11) |

Closed #11 as completed.
