### ISSUE TITLE
请问有没有关于激光加V形槽实现机器人自动回充的实现案例阿

### ISSUE THREAD

**Issue by chocodr** [Mr-Tony921/xju-robot#15]
看完了博主使用二维码辅助定位实现自动回充的视频，感觉技术上是可行的，不过在现实工作场景中，由于光线和二维码可能被遮挡等问题，效果可能会打折扣。现在有通过激光去识别充电装上的特殊结构（如V形槽）来进行辅助定位和回充的，不知道博主是否有了解？

**Comment by Mr-Tony921** [comment]
没有相关的案例，感觉都是识别出来一个pose然后goto
