### ISSUE TITLE
您好，我按照部署视频编译通过后，在运行roslaunch xju_pnc move_base_flex.launch 文件时，遇到了下面的问题，该怎么解决

### ISSUE THREAD

**Issue by jsj441805126** [Mr-Tony921/xju-robot#16]
![屏幕截图 2023-12-08 16:02:51](https://github.com/Mr-Tony921/xju-robot/assets/113965671/f9c79c23-3fa5-428d-8a68-7beebdc49ed6)

**Comment by liyinbei** [comment]
我把代码运行到Gaezbo机器人上时，没有问题。 但部署到一个机器人硬件上时，遇到了相同的问题 (“move base action not online” 和 “exe path action not online!”.) 。 和 Gazebo部署相比，只改动了AMCL的参数，其它没有更改，但出现了该问题，导航不执行，怀疑是costmap出现了问题导致路径不规划。请问有没有解决的思路？ 谢谢

**Comment by Mr-Tony921** [comment]
这个图里是mbf没有找到，要不是环境有问题，要不是代码thirdparty没有下载
