### ISSUE TITLE
编译的时候报错 costmap_core

### ISSUE THREAD

**Issue by teachermaDSM** [Mr-Tony921/xju-robot#18]
fatal error: costmap_2d/keepOutZone.h: 没有那个文件或目录
    7 | #include "costmap_2d/keepOutZone.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

环境是Ubuntu18.04 ros melodic
大佬求帮忙看一下

**Comment by Mr-Tony921** [comment]
https://www.bilibili.com/video/BV19o4y1W7jC/?share_source=copy_web&vd_source=88e435df3261250165e3c0b331a63754\
git submodule init && git submodule update
