### ISSUE TITLE
occur errors when `catkin_make` in noetic

### ISSUE THREAD

**Issue by ChangerC77** [Mr-Tony921/xju-robot#2]
![image](https://user-images.githubusercontent.com/44107275/217864773-2f8a41a1-4b68-47b5-b25d-87d56dafb4e8.png)

**Comment by BIT-XLJ** [comment]
I meet with the same problem in melodic.

**Comment by Mr-Tony921** [comment]
第一个问题，没有找到costmap_2d/keepOutZone.h，是因为xju工程修改了navigation这个package，在submodule里，需要卸载本地的navigation然后用submodule中的即可，地址在https://github.com/Mr-Tony921/navigation.git

第二个问题，是OpenCV版本问题，Melodic的默认版本是3.2.0，noetic应该是3.4.0，换CV版本是可以用的，或者修改explore的程序，改用对的api，如果不用explore，屏蔽掉这个package的编译也可以

**Comment by Mr-Tony921** [comment]
@ChangerC77 @BIT-XLJ 看下有没有解决~

**Comment by Mr-Tony921** [comment]
noetic不在支持范围，且提供了临时方案，关闭问题
