### ISSUE TITLE
执行catkin_make报错

### ISSUE THREAD

**Issue by emo8899** [Mr-Tony921/xju-robot#20]
![image](https://github.com/Mr-Tony921/xju-robot/assets/108335283/ecc0c81c-e5dc-4a26-a57a-7bbf5b016394)
麻烦帮忙看下这个错误，装了很多次都不行

**Comment by kisstheu** [comment]
指定-j 1试下

**Comment by emo8899** [comment]
> 指定-j 1试下

![image](https://github.com/Mr-Tony921/xju-robot/assets/108335283/c2b32145-7614-458e-819f-d4b54b582299)
提示新的报错

**Comment by emo8899** [comment]
已经解决
