### ISSUE TITLE
no path planning in 2d navigation in noetic

### ISSUE THREAD

**Issue by ChangerC77** [Mr-Tony921/xju-robot#4]
The problem of incompatibility of the noetic version before this step has been solved. However, when I tried point-to-point navigation, I found that the navigation could not be performed after a given target point, and the planned route could not appear. I have uninstalled the navigation package. I want to know whether this is related to the ros version?
![image](https://user-images.githubusercontent.com/44107275/223427429-9150130d-b5a4-4a11-bcaa-849a387b8d99.png)

**Comment by Mr-Tony921** [comment]
> The problem of incompatibility of the noetic version before this step has been solved. However, when I tried point-to-point navigation, I found that the navigation could not be performed after a given target point, and the planned route could not appear. I have uninstalled the navigation package. I want to know whether this is related to the ros version? ![image](https://user-images.githubusercontent.com/44107275/223427429-9150130d-b5a4-4a11-bcaa-849a387b8d99.png)

把启动movebase终端的脚本上传看下

**Comment by vanstrong12138** [comment]
> > 解决了此步骤之前 noetic 版本不兼容的问题。但是，当我尝试点对点导航时，我发现在给定目标点之后无法执行导航，并且无法显示计划的路线。我已经卸载了导航包。我想知道这是否与 ros 版本有关？![图像](https://user-images.githubusercontent.com/44107275/223427429-9150130d-b5a4-4a11-bcaa-849a387b8d99.png)
> 
> 把启动movebase终端的脚本上传看下
![Screenshot from 2023-03-26 19-15-28](https://user-images.githubusercontent.com/94519379/227772062-e60484e2-4da4-461f-9d95-881018d2c58c.png)
我也是发布导航点之后没有反应，终端说chmod +x ，我给所有文件加了权限之后也一样是这个报错

**Comment by Mr-Tony921** [comment]
> > > 解决了此步骤之前 noetic 版本不兼容的问题。但是，当我尝试点对点导航时，我发现在给定目标点之后无法执行导航，并且无法显示计划的路线。我已经卸载了导航包。我想知道这是否与 ros 版本有关？![图像](https://user-images.githubusercontent.com/44107275/223427429-9150130d-b5a4-4a11-bcaa-849a387b8d99.png)
> > 
> > 
> > 把启动movebase终端的脚本上传看下
> > ![Screenshot from 2023-03-26 19-15-28](https://user-images.githubusercontent.com/94519379/227772062-e60484e2-4da4-461f-9d95-881018d2c58c.png)
> > 我也是发布导航点之后没有反应，终端说chmod +x ，我给所有文件加了权限之后也一样是这个报错

mbf安装有问题吧，是不是分支没切成20.04，或者你用movebase脚本试试

**Comment by ChangerC77** [comment]
不好意思之前一直在忙着考试，我现在更新我的终端界面
![image](https://user-images.githubusercontent.com/44107275/236637434-1e0be961-dc95-4598-8462-47bd36e97244.png)
运行的指令是
roslaunch xju_simu simple_world.launch
roslaunch xju_pnc move_base.launch

git分支
![image](https://user-images.githubusercontent.com/44107275/236637541-d5990259-a492-4a6d-ad95-6d124e2f5e48.png)
视频里面对启动的流程感觉不是很清楚，能不能麻烦您更新一个启动的指令顺序，谢谢
