### ISSUE TITLE
A more accurate ackermann control model

### ISSUE THREAD

**Issue by cdefg** [Mr-Tony921/xju-robot#9]
The ackermann control in your code `servo_command.py` means:
1. the drive wheels share the same velocity
2. the front wheels share the same steering angle
I think that's enough for most low speed circumstance.
Yet for a more accurate model, you can modify it like
[accurate ](https://github.com/cdefg/ackermann_simu.git)

I've added nonlinear factor in case of 0 throttle input with non-0 output (like diff-drive vehicle), the code is like below:

```
throttle = data.drive.speed
steer = data.drive.steering_angle # angular velocity in fact

if abs(steer) < steer_threshold:
        pub_vel_left_rear_wheel.publish(throttle * 31.75)
        pub_vel_right_rear_wheel.publish(throttle * 31.75)
        pub_pos_left_steering_hinge.publish(steer)
        pub_pos_right_steering_hinge.publish(steer)

        rospy.loginfo("throttle(target velocity): %f", throttle* 31.75)
        rospy.loginfo("steer(target angular velocity): %f", steer)
    elif ( abs(throttle) > abs(steer * d)):
        throttle_left = (throttle - steer * d) * 31.75
        throttle_right = (throttle + steer * d) * 31.75
        R = throttle/steer
        if (R < 0):
            steer_left = math.atan2(l, R + d) - math.pi
            steer_right = math.atan2(l, R - d) - math.pi
        else:
            steer_left  = math.atan2(l, R - d)
            steer_right = math.atan2(l, R + d)
        pub_vel_left_rear_wheel.publish(throttle_left)
        pub_vel_right_rear_wheel.publish(throttle_right)
        pub_pos_left_steering_hinge.publish(steer_left)
        pub_pos_right_steering_hinge.publish(steer_right)

        rospy.loginfo("throttle_left: %f", throttle_left)
        rospy.loginfo("throttle_right: %f", throttle_right)
        rospy.loginfo("steer_left: %f", steer_left)
        rospy.loginfo("steer_right: %f", steer_right)
    else:
        pub_vel_left_rear_wheel.publish(throttle * 31.75)
        pub_vel_right_rear_wheel.publish(throttle * 31.75)
        pub_pos_left_steering_hinge.publish(steer)
        pub_pos_right_steering_hinge.publish(steer)

        rospy.loginfo("throttle(target velocity): %f", throttle* 31.75)
        rospy.loginfo("steer(target angular velocity): %f", steer)
```
I've tested it with teleop tools in gazebo, it seems working well.

By the way, I wonder why there's a 31.75 product factor in throttle.

I would be very appreciating your consideration of testing this model.

**Comment by cdefg** [comment]
And I might found a reason for problem in your video.
You mentioned in teb-local-planner, sometimes the vehicle failed to continue to move. I think the possible reason is that the model is trying to move in unsuitable (for ackermann model) trajectory. The turn is too sharp. But the vehicle control algorithm is still trying to turn around by your diff-drive way. And this causes great friction and may lead to fail.

This is just a guess. And I guess if you modify control according to my suggestions above, the vehicle might fail more. And I guess if we want to make it perfect, we have to give better local plan results. 

I will try to validate my guess by testing with the planning algorithms. And try to fix the algorithms.

**Comment by Mr-Tony921** [comment]
Thanks for watching.
The problem in video is found, please try my latest update.
As for steering angle, I think it's just focus on the steering wheel (joint), doesn't matter with the turning radius. 
teb_local_planner already did something about it, check [here](https://github.com/rst-tu-dortmund/teb_local_planner/blob/0e839074c3407ff9ee2206a49567a20bd49fd8cc/scripts/cmd_vel_to_ackermann_drive.py)

**Comment by cdefg** [comment]
And the 31.75 factor? Is it just a control gain? :)

**Comment by cdefg** [comment]
And I have an advice : change the p gain in param file `ackermann_control.yaml` . I changed it to 100 and it behaves "harder" 
from friction punctuation and has faster reaction.
